### ISSUE TITLE
custhelp.com

### ISSUE THREAD

**Issue by iBaldie** [rajangdavis/osvc_php#2]
Config.php line 52, the custhelp.com url braks use for other instances and is not required:

$base_url .= "/services/rest/connect/";

**Comment by rajangdavis** [comment]
What exactly are you looking to accomplish here?

Can you provide a use case for the change you are requesting?

I would prefer to add a "domain" option for changing the domain that could be passed into the Client class and have tests for it. 

In my opinion, removing "custhelp" from the domain is not a very elegant solution in that you would have to specify the domain in the "interface" option. This is a little bit messier solution than I would like, but I am open to making a change so that a different domain can be passed in.

**Comment by iBaldie** [comment]
Hi
Yes I am using it for a clients domain and setting the Site option to the clients url, however the custhelp.com throws an error as the url is invalid when concatenated, or I could be missing something...

**Comment by rajangdavis** [comment]
@iBaldie before I can make any changes, I need to secure a test site and credentials for that test site that I can run my test suite against. I don't know how long this will take, so please be patient.

What I would suggest is using your forked version for now; what you can do is put the site URL in the interface section as follows:

```require __DIR__ . '/vendor/autoload.php';

$rn_client = new OSvCPHP\Client(array(
	"username" => getenv("OSC_ADMIN"),			
	"password" => getenv("OSC_PASSWORD"),
	"interface" => "<subdomain.domain.topleveldomain>"   #=> eg. "www.customerdomain.com"
));
```

When I get a test site up and running, I will add something like the following to satisfy your requirements:

```require __DIR__ . '/vendor/autoload.php';

$rn_client = new OSvCPHP\Client(array(
	"username" => getenv("OSC_ADMIN"),			
	"password" => getenv("OSC_PASSWORD"),
	"domain" => "<subdomain.domain.topleveldomain>"   #=> eg. "www.customerdomain.com"
));
```

Majority of the time, a customer will have a custhelp domain which is why I have set up the library the way it's set up.

Please note, there are still some changes that I will be making in the library; however, these changes will automate setting the access token to improve the quality of service as well as pushing certain settings out of the client class and into optional parameters.

**Comment by h43r1c** [comment]
I too had a similar need.  I do not have access to a git client at work but I made the following changes to implement this in a more generic way:

Starting at line 20 of Config.php
> 		if(isset($config_hash['demo_site']) && $config_hash['demo_site'] === true){
>			$base_url .= "rightnowdemo.com/services/rest/connect/";
>		}else if(strpos($config_hash['interface'], "https://") === 0){
>			$base_url = $config_hash['interface'] . "/services/rest/connect/";
>		}else{
>			$base_url .= "custhelp.com/services/rest/connect/";
>		}

Requires the fully qualified address to tell the difference between those that need it or simply need the third level.

**Comment by rajangdavis** [comment]
@h43r1c I like this recommendation. 

The only issue that I have is that I do not have a test site to run tests against in order to merge such a change.

I am working on securing a site, but I may not be able to maintain or make changes to my libraries until I do so.

**Comment by rajangdavis** [comment]
@iBaldie @h43r1c 

I am aiming to incorporate changes to support this request by this weekend. I need to adjust some things in my test suite but once I have that figured out, the library should support custom domains.

I am also planning on making some breaking changes, but these will be in a different commit than the above change.

**Comment by rajangdavis** [comment]
@iBaldie @h43r1c

[I have added support for a custom domain in release version 1.1.2](https://github.com/rajangdavis/osvc_php/releases/tag/v1.1.2).

The way this will work as follows:


```
$rn_client = new OSvCPHP\Client(array(
	"username" => getenv("OSC_ADMIN"),			
	"password" => getenv("OSC_PASSWORD"),
	"custom_domain" => "<subdomain.domain.topleveldomain>"   #=> eg. "www.customerdomain.com"
));
```
I just tested this and it should work. If you have any issues, I will give you a week to raise them, otherwise I will close out this issue.
